Fix #3 README.md
TerenceNg03/CI-Server pull request #37
Opened 2024-02-12 18:53 UTC by jsoderholm

Closes #3

2024-02-12 21:12 UTC, TerenceNg03 commented on README.md
> +
- Implement web request handling
- Implement post commit status
- Set up project

2024-02-13 16:26 UTC, tohanss approved these changes

2024-02-13 16:26 UTC, tohanss commented on README.md
> +
* Implement Git cloning of related repo

2024-02-13 17:07 UTC, Ceevtj commented on README.md
> +- Lorem Ipsum
```suggestion
- Implement functionality for compiling and testing branch
```

2024-02-13 17:53 UTC, angelicaengstrom requested changes, later dismissed

2024-02-13 17:53 UTC, angelicaengstrom commented on README.md
> +- Lorem Ipsum
- Implement CI feature for automatic testing
- Implement output of CI features

2024-02-13 18:10 UTC, merged